# Site Settings
title: ScaleConfCo
email: hola@scaleconfco.com
description: ""
baseurl: "/"
url: "https://scaleconfco.com/"
twitter_username: scaleconfco
github_username:  ScaleConfCo

# Build settings
plugins:
  - jekyll-feed
